image: "node:8.11"

before_script:
  - node --version
  - npm i -g yarn && chmod +x /usr/local/lib/node_modules/yarn/bin/yarn.js
  - yarn install

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

mocha:
  script:
    - yarn test
